package com.zuel.fleamarket.model;

import com.zuel.fleamarket.model.base.BaseCaptchas;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Captchas extends BaseCaptchas<Captchas> {
	public static final Captchas dao = new Captchas().dao();
}
