package com.zuel.fleamarket.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public void setComId(java.lang.Integer comId) {
		set("com_id", comId);
	}
	
	public java.lang.Integer getComId() {
		return getInt("com_id");
	}

	public void setComGId(java.lang.Integer comGId) {
		set("com_g_id", comGId);
	}
	
	public java.lang.Integer getComGId() {
		return getInt("com_g_id");
	}

	public void setComUId(java.lang.Integer comUId) {
		set("com_u_id", comUId);
	}
	
	public java.lang.Integer getComUId() {
		return getInt("com_u_id");
	}

	public void setComDesc(java.lang.String comDesc) {
		set("com_desc", comDesc);
	}
	
	public java.lang.String getComDesc() {
		return getStr("com_desc");
	}

	public void setComReply(java.lang.Integer comReply) {
		set("com_reply", comReply);
	}
	
	public java.lang.Integer getComReply() {
		return getInt("com_reply");
	}

	public void setComAddtime(java.util.Date comAddtime) {
		set("com_addtime", comAddtime);
	}
	
	public java.util.Date getComAddtime() {
		return get("com_addtime");
	}

	public void setComUpdatetime(java.util.Date comUpdatetime) {
		set("com_updatetime", comUpdatetime);
	}
	
	public java.util.Date getComUpdatetime() {
		return get("com_updatetime");
	}

}
