package com.zuel.fleamarket.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCaptchas<M extends BaseCaptchas<M>> extends Model<M> implements IBean {

	public void setCapId(java.lang.Integer capId) {
		set("cap_id", capId);
	}
	
	public java.lang.Integer getCapId() {
		return getInt("cap_id");
	}

	public void setCapKey(java.lang.String capKey) {
		set("cap_key", capKey);
	}
	
	public java.lang.String getCapKey() {
		return getStr("cap_key");
	}

	public void setCapValue(java.lang.String capValue) {
		set("cap_value", capValue);
	}
	
	public java.lang.String getCapValue() {
		return getStr("cap_value");
	}

	public void setCapExpire(java.lang.Long capExpire) {
		set("cap_expire", capExpire);
	}
	
	public java.lang.Long getCapExpire() {
		return getLong("cap_expire");
	}

}
