package com.zuel.fleamarket.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUId(java.lang.Integer uId) {
		set("u_id", uId);
	}
	
	public java.lang.Integer getUId() {
		return getInt("u_id");
	}

	public void setUStuid(java.lang.String uStuid) {
		set("u_stuid", uStuid);
	}
	
	public java.lang.String getUStuid() {
		return getStr("u_stuid");
	}

	public void setUPwd(java.lang.String uPwd) {
		set("u_pwd", uPwd);
	}
	
	public java.lang.String getUPwd() {
		return getStr("u_pwd");
	}

	public void setUName(java.lang.String uName) {
		set("u_name", uName);
	}
	
	public java.lang.String getUName() {
		return getStr("u_name");
	}

	public void setUGender(java.lang.String uGender) {
		set("u_gender", uGender);
	}
	
	public java.lang.String getUGender() {
		return getStr("u_gender");
	}

	public void setUPhone(java.lang.String uPhone) {
		set("u_phone", uPhone);
	}
	
	public java.lang.String getUPhone() {
		return getStr("u_phone");
	}

	public void setUQq(java.lang.String uQq) {
		set("u_qq", uQq);
	}
	
	public java.lang.String getUQq() {
		return getStr("u_qq");
	}

	public void setUAddtime(java.util.Date uAddtime) {
		set("u_addtime", uAddtime);
	}
	
	public java.util.Date getUAddtime() {
		return get("u_addtime");
	}

	public void setUUpdatetime(java.util.Date uUpdatetime) {
		set("u_updatetime", uUpdatetime);
	}
	
	public java.util.Date getUUpdatetime() {
		return get("u_updatetime");
	}

}
