package com.zuel.fleamarket.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseImage<M extends BaseImage<M>> extends Model<M> implements IBean {

	public void setIId(java.lang.Integer iId) {
		set("i_id", iId);
	}
	
	public java.lang.Integer getIId() {
		return getInt("i_id");
	}

	public void setIGId(java.lang.Integer iGId) {
		set("i_g_id", iGId);
	}
	
	public java.lang.Integer getIGId() {
		return getInt("i_g_id");
	}

	public void setIPath(java.lang.String iPath) {
		set("i_path", iPath);
	}
	
	public java.lang.String getIPath() {
		return getStr("i_path");
	}

	public void setIAddtime(java.util.Date iAddtime) {
		set("i_addtime", iAddtime);
	}
	
	public java.util.Date getIAddtime() {
		return get("i_addtime");
	}

	public void setIUpdatetime(java.util.Date iUpdatetime) {
		set("i_updatetime", iUpdatetime);
	}
	
	public java.util.Date getIUpdatetime() {
		return get("i_updatetime");
	}

}
