package com.zuel.fleamarket.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public void setGId(java.lang.Integer gId) {
		set("g_id", gId);
	}
	
	public java.lang.Integer getGId() {
		return getInt("g_id");
	}

	public void setGCId(java.lang.Integer gCId) {
		set("g_c_id", gCId);
	}
	
	public java.lang.Integer getGCId() {
		return getInt("g_c_id");
	}

	public void setGUId(java.lang.Integer gUId) {
		set("g_u_id", gUId);
	}
	
	public java.lang.Integer getGUId() {
		return getInt("g_u_id");
	}

	public void setGName(java.lang.String gName) {
		set("g_name", gName);
	}
	
	public java.lang.String getGName() {
		return getStr("g_name");
	}

	public void setGPrice(java.lang.Integer gPrice) {
		set("g_price", gPrice);
	}
	
	public java.lang.Integer getGPrice() {
		return getInt("g_price");
	}

	public void setGRealprice(java.lang.Integer gRealprice) {
		set("g_realprice", gRealprice);
	}
	
	public java.lang.Integer getGRealprice() {
		return getInt("g_realprice");
	}

	public void setGDescribe(java.lang.String gDescribe) {
		set("g_describe", gDescribe);
	}
	
	public java.lang.String getGDescribe() {
		return getStr("g_describe");
	}

	public void setGState(java.lang.Integer gState) {
		set("g_state", gState);
	}
	
	public java.lang.Integer getGState() {
		return getInt("g_state");
	}

	public void setGAddtime(java.util.Date gAddtime) {
		set("g_addtime", gAddtime);
	}
	
	public java.util.Date getGAddtime() {
		return get("g_addtime");
	}

	public void setGUpdatetime(java.util.Date gUpdatetime) {
		set("g_updatetime", gUpdatetime);
	}
	
	public java.util.Date getGUpdatetime() {
		return get("g_updatetime");
	}

}
