package com.zuel.fleamarket.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFollow<M extends BaseFollow<M>> extends Model<M> implements IBean {

	public void setFId(java.lang.Integer fId) {
		set("f_id", fId);
	}
	
	public java.lang.Integer getFId() {
		return getInt("f_id");
	}

	public void setFGId(java.lang.Integer fGId) {
		set("f_g_id", fGId);
	}
	
	public java.lang.Integer getFGId() {
		return getInt("f_g_id");
	}

	public void setFUId(java.lang.Integer fUId) {
		set("f_u_id", fUId);
	}
	
	public java.lang.Integer getFUId() {
		return getInt("f_u_id");
	}

	public void setFAddtime(java.util.Date fAddtime) {
		set("f_addtime", fAddtime);
	}
	
	public java.util.Date getFAddtime() {
		return get("f_addtime");
	}

	public void setFUpdatetime(java.util.Date fUpdatetime) {
		set("f_updatetime", fUpdatetime);
	}
	
	public java.util.Date getFUpdatetime() {
		return get("f_updatetime");
	}

}
